markdown:         rdiscount
pygments:         true
paginate:         4

title:            Mzhong's Site
url:              http://flowerszhong.github.com
feed:             /atom.xml
author:
    name:         PIZn
    email:        flowerszhong@hotmail.com
    description:  "The one theme is another web theme design by PIZn."

about:            "I am matthew.zhong.I love front-end development.be family with AMD & MVC"
follow:
    email:        flowerszhong@gmail.com
    github:       https://flowerszhong.github.com
    twitter:      http://www.twitter.com/flowerszhong
    google:       https://flowerszhong.shop.co
    facebook:     http://facebook.com/flowerszhong
description:      matthew.zhong's site

indexContent:     true
imageLink:        http://www.pizn.net/static/images/20121109Monutain.jpg


style:            /css/style.css
blogName:         mzhong
blogDesc:         matthew.zhong's site
favicon:          /favicon.ico
theme:            default

disqus:           mzhongblog

copyright:        Copyright © 2011-2013 Mzhong All rights reserved.
test:             ok
